package com.hireconnect.dto.request;

import java.math.BigDecimal;
import java.time.LocalDate;

public class PayrollRequest {
    private Long userId;
    private LocalDate payrollMonth;
    private BigDecimal basicSalary;
    private BigDecimal hra;
    private BigDecimal conveyanceAllowance;
    private BigDecimal medicalAllowance;
    private BigDecimal lta;
    private BigDecimal otherAllowances;
    private BigDecimal pfEmployee;
    private BigDecimal pfEmployer;
    private BigDecimal professionalTax;
    private BigDecimal taxDeductions;
    private BigDecimal otherDeductions;
    private Integer lopDays;
    private Integer overtimeHours;
    private String notes;
    private Boolean autoGenerated;
    
    
	public Long getUserId() {
		return userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public LocalDate getPayrollMonth() {
		return payrollMonth;
	}
	public void setPayrollMonth(LocalDate payrollMonth) {
		this.payrollMonth = payrollMonth;
	}
	public BigDecimal getBasicSalary() {
		return basicSalary;
	}
	public void setBasicSalary(BigDecimal basicSalary) {
		this.basicSalary = basicSalary;
	}
	public BigDecimal getHra() {
		return hra;
	}
	public void setHra(BigDecimal hra) {
		this.hra = hra;
	}
	public BigDecimal getConveyanceAllowance() {
		return conveyanceAllowance;
	}
	public void setConveyanceAllowance(BigDecimal conveyanceAllowance) {
		this.conveyanceAllowance = conveyanceAllowance;
	}
	public BigDecimal getMedicalAllowance() {
		return medicalAllowance;
	}
	public void setMedicalAllowance(BigDecimal medicalAllowance) {
		this.medicalAllowance = medicalAllowance;
	}
	public BigDecimal getLta() {
		return lta;
	}
	public void setLta(BigDecimal lta) {
		this.lta = lta;
	}
	public BigDecimal getOtherAllowances() {
		return otherAllowances;
	}
	public void setOtherAllowances(BigDecimal otherAllowances) {
		this.otherAllowances = otherAllowances;
	}

	public BigDecimal getPfEmployee() {
		return pfEmployee;
	}
	public void setPfEmployee(BigDecimal pfEmployee) {
		this.pfEmployee = pfEmployee;
	}
	
	public BigDecimal getPfEmployer() {
		return pfEmployer;
	}
	public void setPfEmployer(BigDecimal pfEmployer) {
		this.pfEmployer = pfEmployer;
	}
	public BigDecimal getProfessionalTax() {
		return professionalTax;
	}
	public void setProfessionalTax(BigDecimal professionalTax) {
		this.professionalTax = professionalTax;
	}
	public BigDecimal getTaxDeductions() {
		return taxDeductions;
	}
	public void setTaxDeductions(BigDecimal taxDeductions) {
		this.taxDeductions = taxDeductions;
	}
	public BigDecimal getOtherDeductions() {
		return otherDeductions;
	}
	public void setOtherDeductions(BigDecimal otherDeductions) {
		this.otherDeductions = otherDeductions;
	}
	public Integer getLopDays() {
		return lopDays;
	}
	public void setLopDays(Integer lopDays) {
		this.lopDays = lopDays;
	}
	public Integer getOvertimeHours() {
		return overtimeHours;
	}
	public void setOvertimeHours(Integer overtimeHours) {
		this.overtimeHours = overtimeHours;
	}
	public String getNotes() {
		return notes;
	}
	public void setNotes(String notes) {
		this.notes = notes;
	}
	public Boolean getAutoGenerated() {
		return autoGenerated;
	}
	public void setAutoGenerated(Boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}  
    
    
}