package com.hireconnect.service;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.hireconnect.dto.request.PayrollRequest;
import com.hireconnect.dto.request.PayrollUpdateRequest;
import com.hireconnect.dto.response.PayrollResponse;
import com.hireconnect.entity.PayrollHistory;
import com.hireconnect.entity.PayrollHistory.PayrollStatus;
import com.hireconnect.entity.User;
import com.hireconnect.repository.PayrollHistoryRepository;
import com.hireconnect.repository.UserRepository;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class PayrollService {
    
    private final PayrollHistoryRepository payrollHistoryRepository;
    private final UserRepository userRepository;
    
    
    private PayrollResponse enrichPayrollWithUserDetails(PayrollHistory payroll) {
        PayrollResponse dto = new PayrollResponse();

        dto.setId(payroll.getId());
        dto.setUserId(payroll.getUserId());
        dto.setPayrollMonth(payroll.getPayrollMonth());

        // ✅ Pay period
        YearMonth ym = YearMonth.from(payroll.getPayrollMonth());
        String payPeriod =
                "01 " + ym.getMonth().name().substring(0, 3) + " " + ym.getYear() +
                " - " +
                ym.lengthOfMonth() + " " + ym.getMonth().name().substring(0, 3) + " " + ym.getYear();
        dto.setPayPeriod(payPeriod);

        /* ===================== EARNINGS ===================== */
        dto.setBasicSalary(payroll.getBasicSalary());
        dto.setHra(payroll.getHra());
        dto.setConveyanceAllowance(payroll.getConveyanceAllowance());
        dto.setMedicalAllowance(payroll.getMedicalAllowance());
        dto.setOtherAllowances(payroll.getOtherAllowances());
        dto.setTotalEarnings(payroll.getTotalEarnings());
        dto.setPfEmployer(payroll.getPfEmployer());

        /* ===================== DEDUCTIONS ===================== */
        dto.setPfEmployee(payroll.getPfEmployee());          
        dto.setProfessionalTax(payroll.getProfessionalTax());
        dto.setTaxDeductions(payroll.getTaxDeductions());
        dto.setOtherDeductions(payroll.getOtherDeductions());
        dto.setTotalDeductions(payroll.getTotalDeductions());

        /* ===================== FINAL ===================== */
        dto.setNetSalary(payroll.getNetSalary());
        dto.setLopDays(payroll.getLopDays());
        dto.setOvertimeHours(payroll.getOvertimeHours());
        dto.setStatus(payroll.getStatus());
        dto.setPaymentDate(payroll.getPaymentDate());
        dto.setPayslipGenerated(payroll.getPayslipGenerated());
        dto.setPayslipPath(payroll.getPayslipPath());
        dto.setAutoGenerated(payroll.getAutoGenerated());
        dto.setRemarks(payroll.getRemarks());
        dto.setCreatedAt(payroll.getCreatedAt());

        try {
            User user = userRepository.findById(payroll.getUserId()).orElse(null);
            if (user != null) {
                dto.setEmployeeId(
                    user.getEmployeeId() != null ? user.getEmployeeId() : "EMP-" + user.getId()
                );
                dto.setEmployeeName(user.getFullName());
                dto.setJoiningDate(user.getCreatedAt());
                dto.setSource(payroll.getAutoGenerated() ? "Auto Generated" : "Manual Entry");

                if (payroll.getPaymentDate() != null) {
                    dto.setPayDate(
                        payroll.getPaymentDate().format(DateTimeFormatter.ofPattern("dd MMM yyyy"))
                    );
                }
            }
        } catch (Exception ignored) {}

        return dto;
    }

    
    private void calculatePayrollAmounts(PayrollHistory p) {

        BigDecimal basic = nz(p.getBasicSalary());
        BigDecimal hra = nz(p.getHra());
        BigDecimal conveyance = nz(p.getConveyanceAllowance());
        BigDecimal medical = nz(p.getMedicalAllowance());
        BigDecimal other = nz(p.getOtherAllowances());

        // ✅ Gross Earnings
        BigDecimal gross =
            basic.add(hra)
                 .add(conveyance)
                 .add(medical)
                 .add(other);
        
        // ✅ Deductions (EMPLOYEE only)
        BigDecimal pfEmployee = nz(p.getPfEmployee());
        BigDecimal incomeTax = nz(p.getTaxDeductions());
        BigDecimal professionalTax = nz(p.getProfessionalTax());
        BigDecimal otherDeductions = nz(p.getOtherDeductions());

        BigDecimal totalDeductions =
                pfEmployee
                .add(incomeTax)
                .add(professionalTax)
                .add(otherDeductions);

        // ✅ Net Salary
        BigDecimal netSalary = gross.subtract(totalDeductions);

        // 🚨 Safety checks
        if (gross.compareTo(BigDecimal.ZERO) < 0) {
            throw new RuntimeException("Gross earnings cannot be negative");
        }
        if (netSalary.compareTo(BigDecimal.ZERO) < 0) {
            throw new RuntimeException("Net salary cannot be negative");
        }

        p.setTotalEarnings(gross);
        p.setTotalDeductions(totalDeductions);
        p.setNetSalary(netSalary);
    }

    private BigDecimal nz(BigDecimal v) {
        return v != null ? v : BigDecimal.ZERO;
    }

    private String money(BigDecimal v) {
        if (v == null) return "Rs. 0.00";
        return "Rs. " + v.setScale(2, RoundingMode.HALF_UP);
    }

    
    
    public List<PayrollResponse> getAllPayrolls() {
        List<PayrollHistory> payrolls = payrollHistoryRepository.findAll();
        return payrolls.stream()
            .map(this::enrichPayrollWithUserDetails)
            .collect(Collectors.toList());
    }
    
    
    public PayrollResponse getPayrollById(Long id) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        return enrichPayrollWithUserDetails(payroll);
    }
    
    
    public List<PayrollResponse> getPayrollByUser(Long userId) {
        List<PayrollHistory> payrolls = payrollHistoryRepository.findByUserIdOrderByPayrollMonthDesc(userId);
        return payrolls.stream()
            .map(this::enrichPayrollWithUserDetails)
            .collect(Collectors.toList());
    }
    
    @Transactional
    public PayrollHistory createPayroll(PayrollRequest request) {

        PayrollHistory payroll = new PayrollHistory();
        mapRequestToEntity(request, payroll);

        // ✅ Check duplicate BEFORE heavy calculation
        payrollHistoryRepository
            .findByUserIdAndMonth(
                payroll.getUserId(),
                payroll.getPayrollMonth()
            )
            .ifPresent(p -> {
                throw new RuntimeException("Payroll already exists for this month");
            });

        // ✅ Then calculate amounts
        calculatePayrollAmounts(payroll);

        return payrollHistoryRepository.save(payroll);
    }


    @Transactional
    public PayrollHistory updatePayroll(Long id, PayrollUpdateRequest request) {

        PayrollHistory payroll = payrollHistoryRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Payroll not found"));

        // Update only editable fields
        if (request.getBasicSalary() != null) {
            payroll.setBasicSalary(request.getBasicSalary());
        }

        if (request.getTotalDeductions() != null) {
            payroll.setOtherDeductions(request.getTotalDeductions());
        }

        if (request.getStatus() != null) {
            payroll.setStatus(PayrollStatus.valueOf(request.getStatus()));
        }

        // ✅ Always recalculate using central logic
        calculatePayrollAmounts(payroll);

        return payrollHistoryRepository.save(payroll);
    }


    
    @Transactional
    public void deletePayroll(Long id) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        payrollHistoryRepository.delete(payroll);
    }
    
    @Transactional
    public PayrollHistory generateAutoPayroll(PayrollRequest request) {
        return createPayroll(request);
    }
    
    @Transactional
    public PayrollHistory manualPayrollEntry(PayrollRequest request) {
        return createPayroll(request);
    }
    
    public Map<String, Object> getAnalytics(String range) {
        Map<String, Object> analytics = new HashMap<>();
        
        long totalEmployees = userRepository.countByRole(User.Role.EMPLOYEE);
        analytics.put("totalEmployees", totalEmployees);
        
        LocalDate now = LocalDate.now();
        LocalDate currentMonth = LocalDate.of(now.getYear(), now.getMonth(), 1);
        List<PayrollHistory> currentMonthPayrolls = payrollHistoryRepository.findByYearAndMonth(
            currentMonth.getYear(), currentMonth.getMonthValue()
        );
        analytics.put("activePayrolls", currentMonthPayrolls.size());
        
        BigDecimal totalPayouts = currentMonthPayrolls.stream()
        		.map(PayrollHistory::getNetSalary)

            .reduce(BigDecimal.ZERO, BigDecimal::add);
        analytics.put("totalPayouts", totalPayouts);
        
        analytics.put("pendingReimbursements", 0);
        
        return analytics;
    }
    
    public ResponseEntity<?> exportPayrolls(String format, String status, String month) {
        List<PayrollHistory> payrolls;
        
        if (!"all".equals(status)) {
            payrolls = payrollHistoryRepository.findByStatus(
                PayrollHistory.PayrollStatus.valueOf(status.toUpperCase())
            );
        } else {
            payrolls = payrollHistoryRepository.findAll();
        }
        
        return ResponseEntity.ok(Map.of("message", "Export functionality to be implemented"));
    }
    
    @Transactional
    public Map<String, Object> generatePayslip(Long payrollId) {

        PayrollHistory payroll = payrollHistoryRepository.findById(payrollId)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + payrollId));

        // ✅ Prevent duplicate payslip generation
        if (Boolean.TRUE.equals(payroll.getPayslipGenerated())) {
            throw new RuntimeException("Payslip already generated for this payroll");
        }

        if (payroll.getPayrollMonth() == null) {
            throw new RuntimeException("Payroll month is missing");
        }

        User user = userRepository.findById(payroll.getUserId())
            .orElseThrow(() -> new RuntimeException("User not found"));

        File uploadsDir = new File("uploads/payslips");
        if (!uploadsDir.exists()) {
            uploadsDir.mkdirs();
        }

        String fileName = "payslip_" + payroll.getUserId() + "_" +
            payroll.getPayrollMonth().format(DateTimeFormatter.ofPattern("yyyy_MM")) + ".pdf";

        String filePath = "uploads/payslips/" + fileName;

        // ✅ PDF generation wrapped safely
        try {
            generatePayslipPDF(payroll, user, filePath);
        } catch (IOException | DocumentException e) {
            throw new RuntimeException("Failed to generate payslip PDF", e);
        }

        payroll.setPayslipGenerated(true);
        payroll.setPayslipPath("/uploads/payslips/" + fileName);
        payrollHistoryRepository.save(payroll);

        Map<String, Object> result = new HashMap<>();
        result.put("message", "Payslip generated successfully");
        result.put("filePath", "/uploads/payslips/" + fileName);

        return result;
    }

    @Transactional(readOnly = true)
    public ResponseEntity<Resource> downloadPayslip(Long payrollId, User principal) {

        PayrollHistory payroll = payrollHistoryRepository.findById(payrollId)
            .orElseThrow(() -> new RuntimeException("Payroll not found"));

        // 🔐 Authorization check
        if (principal.getRole() == User.Role.EMPLOYEE &&
            !payroll.getUserId().equals(principal.getId())) {
            throw new AccessDeniedException("Not allowed to access this payslip");
        }

        if (!Boolean.TRUE.equals(payroll.getPayslipGenerated())) {
            throw new RuntimeException("Payslip not generated");
        }

        File file = new File("." + payroll.getPayslipPath());
        if (!file.exists()) {
            throw new RuntimeException("Payslip file missing");
        }

        Resource resource = new FileSystemResource(file);

        return ResponseEntity.ok()
            .contentType(MediaType.APPLICATION_PDF)
            .header(
                HttpHeaders.CONTENT_DISPOSITION,
                "attachment; filename=\"" + file.getName() + "\""
            )
            .body(resource);
    }


    private void mapRequestToEntity(PayrollRequest request, PayrollHistory payroll) {

        payroll.setUserId(request.getUserId());

        User user = userRepository.findById(request.getUserId())
                .orElseThrow(() -> new RuntimeException("User not found"));
        payroll.setUserName(user.getFullName());

        payroll.setPayrollMonth(request.getPayrollMonth());
        payroll.setBasicSalary(request.getBasicSalary());
        payroll.setHra(request.getHra() != null ? request.getHra() : BigDecimal.ZERO);
        payroll.setConveyanceAllowance(
                request.getConveyanceAllowance() != null ? request.getConveyanceAllowance() : BigDecimal.ZERO
        );
        payroll.setMedicalAllowance(
                request.getMedicalAllowance() != null ? request.getMedicalAllowance() : BigDecimal.ZERO
        );
        payroll.setLta(request.getLta() != null ? request.getLta() : BigDecimal.ZERO);
        payroll.setOtherAllowances(
                request.getOtherAllowances() != null ? request.getOtherAllowances() : BigDecimal.ZERO
        );

        // ✅ Employee PF (DEDuction)
        BigDecimal pfEmployee =
                request.getPfEmployee() != null ? request.getPfEmployee() : BigDecimal.ZERO;
        payroll.setPfEmployee(pfEmployee);

        // ✅ Employer PF (CTC info only)
        BigDecimal pfEmployer =
                request.getPfEmployer() != null ? request.getPfEmployer() : BigDecimal.ZERO;

        // 🔒 Safety: prevent accidental duplication
        if (pfEmployer.compareTo(pfEmployee) == 0 && pfEmployer.compareTo(BigDecimal.ZERO) > 0) {
            pfEmployer = BigDecimal.ZERO;
        }
        payroll.setPfEmployer(pfEmployer);

        payroll.setProfessionalTax(
                request.getProfessionalTax() != null ? request.getProfessionalTax() : BigDecimal.ZERO
        );
        payroll.setTaxDeductions(
                request.getTaxDeductions() != null ? request.getTaxDeductions() : BigDecimal.ZERO
        );
        payroll.setOtherDeductions(
                request.getOtherDeductions() != null ? request.getOtherDeductions() : BigDecimal.ZERO
        );

        payroll.setLopDays(request.getLopDays());
        payroll.setOvertimeHours(request.getOvertimeHours());
        payroll.setAutoGenerated(request.getAutoGenerated());
        payroll.setRemarks(request.getNotes());
    }

    
    private void generatePayslipPDF(PayrollHistory payroll, User user, String filePath) 
            throws IOException, DocumentException {
        
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        document.open();
        
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
        Paragraph title = new Paragraph("PAYSLIP", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        
        document.add(new Paragraph("\n"));
        
        String employeeId = user.getEmployeeId() != null ? user.getEmployeeId() : "EMP-" + user.getId();
        document.add(new Paragraph("Employee Name: " + user.getFullName()));
        document.add(new Paragraph("Employee ID: " + employeeId));
        document.add(new Paragraph("Joining Date: " + (user.getCreatedAt() != null ? 
            user.getCreatedAt().format(DateTimeFormatter.ofPattern("dd MMM yyyy")) : "N/A")));
        document.add(new Paragraph("Month: " + payroll.getPayrollMonth().format(
            DateTimeFormatter.ofPattern("MMMM yyyy"))));
        
        document.add(new Paragraph("\n"));
        
        Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
        
        PdfPTable earningsTable = new PdfPTable(2);
        earningsTable.setWidthPercentage(100);
        
        addTableHeader(earningsTable, "EARNINGS", boldFont);

        addTableRow(earningsTable, "Basic Salary", money(payroll.getBasicSalary()));
        addTableRow(earningsTable, "HRA", money(payroll.getHra()));
        addTableRow(earningsTable, "Conveyance", money(payroll.getConveyanceAllowance()));
        addTableRow(earningsTable, "Medical", money(payroll.getMedicalAllowance()));
        addTableRow(earningsTable, "LTA", money(payroll.getLta()));
        addTableRow(earningsTable, "Other Allowances", money(payroll.getOtherAllowances()));
        addTableRow(earningsTable, "Employer PF Contribution", money(payroll.getPfEmployer()));
        addTableRow(earningsTable, "Total Earnings", money(payroll.getTotalEarnings()));
        
        
        document.add(earningsTable);
        document.add(new Paragraph("\n"));
        
        PdfPTable deductionsTable = new PdfPTable(2);
        deductionsTable.setWidthPercentage(100);
        
        addTableHeader(deductionsTable, "DEDUCTIONS", boldFont);

        addTableRow(deductionsTable, "PF", money(payroll.getPfEmployee()));
        addTableRow(deductionsTable, "Professional Tax", money(payroll.getProfessionalTax()));
        addTableRow(deductionsTable, "Income Tax", money(payroll.getTaxDeductions()));
        addTableRow(deductionsTable, "Other Deductions", money(payroll.getOtherDeductions()));
        addTableRow(deductionsTable, "Total Deductions", money(payroll.getTotalDeductions()));

        
        document.add(deductionsTable);
        document.add(new Paragraph("\n"));
        
        Font netSalaryFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
        Paragraph netSalary = new Paragraph(
        	    "Net Salary: " + money(payroll.getNetSalary()), netSalaryFont);
        netSalary.setAlignment(Element.ALIGN_RIGHT);
        document.add(netSalary);
        
        document.close();
    }
    
    private void addTableRow(PdfPTable table, String label, String value) {
        table.addCell(label);
        table.addCell(value);
    }
    
    private void addTableHeader(PdfPTable table, String header, Font font) {
        PdfPCell cell = new PdfPCell(new Paragraph(header, font));
        cell.setColspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }
    
}
