import React, { useState, useEffect, useCallback } from "react";
import axios from "axios";
import { ArrowLeft, Eye, FileText, Save, Calendar } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Safe API base URL resolver (works for localhost + prod, no `process` crash)
const getApiBaseUrl = () => {
  // 1) Vite env
  try {
    if (
      typeof import.meta !== "undefined" &&
      import.meta.env &&
      import.meta.env.VITE_API_BASE_URL
    ) {
      return import.meta.env.VITE_API_BASE_URL;
    }
  } catch {
    // ignore
  }

  

  // 2) Optional global override
  if (typeof window !== "undefined" && window.__API_BASE_URL__) {
    return window.__API_BASE_URL__;
  }

  // 3) Fallbacks based on current origin
  if (typeof window !== "undefined") {
    if (window.location.hostname === "localhost") {
      return "http://localhost:8080";
    }
    return `${window.location.protocol}//${window.location.host}`;
  }

  return "";
};

export default function ManualEntry({ onBack}) {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    userId: "",
    payrollMonth: "",

    basicSalary: "",
    hra: "",
    conveyanceAllowance: "",
    medicalAllowance: "",
    lta: "",
    otherAllowances: "",
    specialAllowance: "",

    pfEmployee: "",
    pfEmployer: "",
    professionalTax: "",
    taxDeductions: "",
    otherDeductions: "",

    lopDays: 0,
    overtimeHours: 0,

    notes: "",
    autoGenerated: false,
    totalEarnings: 0,
    totalDeductions: 0,
  });

  const [netSalary, setNetSalary] = useState(0);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
  const earnings = [
    formData.basicSalary,
    formData.hra,
    formData.conveyanceAllowance,
    formData.medicalAllowance,
    formData.lta,
    formData.otherAllowances,
    formData.specialAllowance,
  ].map(v => Number(v) || 0);

  const deductions = [
    formData.pfEmployee,
    formData.professionalTax,
    formData.taxDeductions,
    formData.otherDeductions,
  ].map(v => Number(v) || 0);

  const totalEarnings = earnings.reduce((a, b) => a + b, 0);
  const totalDeductions = deductions.reduce((a, b) => a + b, 0);

  setFormData(prev => ({
    ...prev,
    totalEarnings,
    totalDeductions,
  }));

  setNetSalary(totalEarnings - totalDeductions);
}, [
  formData.basicSalary,
  formData.hra,
  formData.conveyanceAllowance,
  formData.medicalAllowance,
  formData.lta,
  formData.otherAllowances,
  formData.specialAllowance,
  formData.pfEmployee,
  formData.professionalTax,
  formData.taxDeductions,
  formData.otherDeductions,
]);




  // Employees fetched from backend
  const [employees, setEmployees] = useState([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);
  const [employeesError, setEmployeesError] = useState("");
const fetchEmployees = useCallback(async () => {
  try {
    setEmployeesLoading(true);
    setEmployeesError("");

    const baseUrl = getApiBaseUrl();

    const res = await axios.get(`${baseUrl}/api/users`, {
      withCredentials: true,
    });

    const data = res.data;

    let employeesList = [];
    if (Array.isArray(data)) employeesList = data;
    else if (Array.isArray(data.users)) employeesList = data.users;
    else if (Array.isArray(data.content)) employeesList = data.content;
    else if (Array.isArray(data.data)) employeesList = data.data;

    setEmployees(employeesList);
  } catch (err) {
    console.error("Error fetching employees:", err);
    setEmployeesError(err.message || "Failed to load employees.");
    toast.error("Failed to load employees list.");
  } finally {
    setEmployeesLoading(false);
  }
}, []);

useEffect(() => {
  fetchEmployees();
}, [fetchEmployees]);


  // -----------------------------
  // HANDLE FORM INPUT
  // -----------------------------
  const numericFields = [
    "basicSalary",
    "hra",
    "conveyanceAllowance",
    "medicalAllowance",
    "lta",
    "otherAllowances",
    "specialAllowance",
    "pfEmployee",
    "pfEmployer",
    "professionalTax",
    "taxDeductions",
    "otherDeductions",
    "lopDays",
    "overtimeHours",
  ];

  const handleInputChange = (e) => {
    const { name, value } = e.target;

    // string fields
    if (!numericFields.includes(name)) {
      const updated = { ...formData, [name]: value };
      setFormData(updated);
      return;
    }

    // numeric fields
    const cleaned = value === "" ? "" : Number(value);
    const updated = { ...formData, [name]: cleaned };
    setFormData(updated);
  };


  // -----------------------------
  // VALIDATION
  // -----------------------------
  const validateForm = () => {
    const errors = [];

    if (!formData.userId) {
      errors.push("Please select an employee.");
    }

    if (!formData.payrollMonth) {
      errors.push("Please select payroll month.");
    }

    if (!formData.basicSalary || Number(formData.basicSalary) <= 0) {
      errors.push("Basic salary must be greater than 0.");
    }

    if (Number.isNaN(netSalary)) {
      errors.push("Net salary calculation is invalid.");
    }

    return errors;
  };

  // -----------------------------
  // SAVE PAYROLL (REAL API)
  // -----------------------------
  
  const handleSavePayroll = async () => {
    const errors = validateForm();
    if (errors.length > 0) {
      toast.error(errors[0], {
        position: "top-right",
        autoClose: 2000,
        theme: "colored",
      });
      return;
    }

    
    const payload = {
      userId: Number(formData.userId),
      payrollMonth: formData.payrollMonth,

      basicSalary: Number(formData.basicSalary) || 0,
      hra: Number(formData.hra) || 0,
      conveyanceAllowance: Number(formData.conveyanceAllowance) || 0,
      medicalAllowance: Number(formData.medicalAllowance) || 0,
      lta: Number(formData.lta) || 0,
      otherAllowances: Number(formData.otherAllowances) || 0,

      pfEmployee: Number(formData.pfEmployee) || 0,
      pfEmployer: Number(formData.pfEmployer) || 0,
      professionalTax: Number(formData.professionalTax) || 0,
      taxDeductions: Number(formData.taxDeductions) || 0,
      otherDeductions: Number(formData.otherDeductions) || 0,

      totalEarnings: formData.totalEarnings || 0,
      totalDeductions: formData.totalDeductions || 0,
      netSalary: netSalary || 0,
      specialAllowance: Number(formData.specialAllowance) || 0,
      lopDays: Number(formData.lopDays) || 0,
      overtimeHours: Number(formData.overtimeHours) || 0,

      notes: formData.notes,
      autoGenerated: false,
    };

  try {
    setSaving(true); // 🔴 START LOCK

    const baseUrl = getApiBaseUrl();

    await axios.post(
      `${baseUrl}/api/payroll/manual-entry`,
      payload,
      { withCredentials: true }
    );

    toast.success("Payroll entry saved successfully!", {
      position: "top-right",
      autoClose: 2000,
      theme: "colored",
    });

  } 
  
  catch (error) {
    toast.error(
      "Something went wrong: " + (error.message || "Unknown error"),
      { autoClose: 2000 }
    );
  } finally {
    setSaving(false); // 🟢 RELEASE LOCK
  }
};

  return (
    <div className="w-full h-full bg-[#F9FAFF] p-6">
      {/* HEADER */}
      <div className="mb-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
        <button
          className="flex items-center gap-2 text-[#011A8B] text-sm font-medium hover:underline"
          onClick={onBack}
        >
          <ArrowLeft size={18} /> Back to Finance Dashboard
        </button>

        <div className="mt-4 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-[#011A8B]">
              Manual Payroll Entry
            </h1>
            <p className="text-sm text-gray-500">
              Individual salary entry system
            </p>
          </div>

          <div className="flex gap-3">
            <button className="flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm text-gray-700 shadow-sm hover:bg-gray-50">
              <Eye size={18} /> Preview Mode
            </button>

            <button
              onClick={() => navigate("/admin/payroll-management")}
              className="flex items-center gap-2 rounded-xl bg-[#011A8B] px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-[#020f5d]"
            >
              <FileText size={18} /> View All Payrolls
            </button>
          </div>
        </div>
      </div>

      {/* FORM GRID */}
      <div className="grid gap-6 lg:grid-cols-3">
        {/* LEFT COLUMN - EMPLOYEE SELECTION */}
        <div className="rounded-2xl border border-gray-200 bg-white shadow-sm">
          <div className="border-b border-gray-100 bg-[#F3F4FF] px-6 py-3 rounded-t-2xl">
            <h3 className="text-sm font-semibold text-[#011A8B]">
              Employee Selection
            </h3>
          </div>

          <div className="p-6 bg-[#F9FAFF] rounded-b-2xl space-y-4">
            <div>
              <label className="text-xs font-medium text-gray-600">
                Select Employee
              </label>
              <select
                name="userId"
                className="mt-1 w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                value={formData.userId}
                onChange={handleInputChange}
              >
                <option value="">
                  {employeesLoading
                    ? "Loading employees..."
                    : "Choose an employee"}
                </option>
                {employeesError && (
                  <option disabled value="">
                    {employeesError}
                  </option>
                )}
                {employees.length === 0 &&
                  !employeesLoading &&
                  !employeesError && (
                    <option disabled value="">
                      No employees found
                    </option>
                  )}
                {employees.map((emp) => (
                  <option key={emp.id} value={emp.id}>
                    {emp.fullName || emp.name || emp.email || `Emp #${emp.id}`}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="text-xs font-medium text-gray-600">
                Payroll Month
              </label>
              <div className="relative mt-1">
                <input
                  type="date"
                  name="payrollMonth"
                  value={formData.payrollMonth}
                  onChange={handleInputChange}
                  className="w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                />
                <Calendar
                  className="absolute right-3 top-2.5 text-gray-400"
                  size={18}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs font-medium text-gray-600">
                  LOP Days
                </label>
                <input
                  type="number"
                  name="lopDays"
                  value={formData.lopDays}
                  onChange={handleInputChange}
                  className="mt-1 w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                />
              </div>

              <div>
                <label className="text-xs font-medium text-gray-600">
                  Overtime Hours
                </label>
                <input
                  type="number"
                  name="overtimeHours"
                  value={formData.overtimeHours}
                  onChange={handleInputChange}
                  className="mt-1 w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                />
              </div>
            </div>

            <div>
              <label className="text-xs font-medium text-gray-600">
                Notes
              </label>
              <textarea
                name="notes"
                value={formData.notes}
                onChange={handleInputChange}
                className="mt-1 w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm h-24 focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                placeholder="Additional notes..."
              />
            </div>
          </div>
        </div>

        {/* MIDDLE COLUMN - SALARY COMPONENTS */}
        <div className="rounded-2xl border border-gray-200 bg-white shadow-sm">
          <div className="border-b border-gray-100 bg-[#F3F4FF] px-6 py-3 rounded-t-2xl">
            <h3 className="text-sm font-semibold text-[#011A8B]">
              Salary Components
            </h3>
          </div>

          <div className="p-6 bg-[#F9FAFF] rounded-b-2xl space-y-4">
            <div>
              <label className="text-xs font-medium text-gray-600">
                Basic Salary
              </label>
              <input
                type="number"
                name="basicSalary"
                className="mt-1 w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                value={formData.basicSalary}
                onChange={handleInputChange}
              />
            </div>

            {[
              ["hra", "HRA"],
              ["conveyanceAllowance", "Conveyance Allowance"],
              ["medicalAllowance", "Medical Allowance"],
              ["lta", "LTA"],
              ["specialAllowance", "Special Allowance"],
              ["otherAllowances", "Other Allowances"],
              ["pfEmployer", "Employer PF Contribution"],
            ].map(([field, label]) => (
              <div key={field}>
                <label className="text-xs font-medium text-gray-600">
                  {label}
                </label>
                <input
                  name={field}
                  type="number"
                  value={formData[field]}
                  onChange={handleInputChange}
                  className="mt-1 w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm bg-white focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                />
              </div>
            ))}

            <div className="pt-2 border-t border-gray-200 mt-2">
              <h4 className="text-xs font-semibold text-gray-700 mb-2">
                Deductions
              </h4>

              {[
                ["pfEmployee", "Provident Fund"],
                ["professionalTax", "Professional Tax"],
                ["taxDeductions", "Tax Deductions"],
                ["otherDeductions", "Other Deductions"],

              ].map(([field, label]) => (
                <div key={field} className="mt-2">
                  <label className="text-xs font-medium text-gray-600">
                    {label}
                  </label>
                  <input
                    type="number"
                    name={field}
                    value={formData[field]}
                    onChange={handleInputChange}
                    className="mt-1 w-full rounded-xl border border-gray-200 bg-white p-2.5 text-sm focus:ring-[#011A8B] focus:border-[#011A8B] text-gray-900"
                  />
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN - SUMMARY */}
        <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
          <h3 className="text-sm font-semibold text-[#011A8B] mb-4">
            Salary Summary
          </h3>

          <p className="text-sm text-gray-600">
            Total Earnings:
            <span className="font-semibold text-gray-900">
              {" "}
              ₹{(formData.totalEarnings || 0).toLocaleString("en-IN")}
            </span>
          </p>

          <p className="mt-2 text-sm text-gray-600">
            Total Deductions:
            <span className="font-semibold text-gray-900">
              {" "}
              ₹{(formData.totalDeductions || 0).toLocaleString("en-IN")}
            </span>
          </p>

          <div className="mt-6 rounded-2xl bg-[#EEF0FF] p-6 text-center text-3xl font-bold text-[#011A8B] shadow-inner">
            ₹{netSalary.toLocaleString("en-IN")}
          </div>

<button
  disabled={saving}
  className={`mt-6 flex w-full items-center justify-center gap-2 rounded-xl
    ${saving ? "bg-gray-400 cursor-not-allowed" : "bg-[#011A8B] hover:bg-[#020f5d]"}
    px-4 py-3 text-sm font-medium text-white shadow-sm`}
  onClick={handleSavePayroll}
>
  <Save size={18} />
  {saving ? "Saving..." : "Save Payroll Entry"}
</button>

          <button
            className="mt-3 w-full rounded-xl border border-gray-300 bg-white px-4 py-3 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50"
            onClick={() => navigate("/admin/payroll-management")}
          >
            View All Payrolls
          </button>
        </div>
      </div>

      <ToastContainer />
    </div>
  );
}