import React, { useState, useEffect, useCallback, useMemo } from "react";
import {
  Eye,
  Edit,
  Trash2,
  Search,
  ArrowLeft,
  RefreshCw,
  Plus,
  FileText,
  Loader2,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

import axios from "axios";

const getApiBaseUrl = () => {
  try {
    if (import.meta?.env?.VITE_API_BASE_URL) {
      return import.meta.env.VITE_API_BASE_URL;
    }
  } catch{
   // not running in Vite env
  }

  if (typeof window !== "undefined") {
    if (window.location.hostname === "localhost") {
      return "http://localhost:8080";
    }
    return `${window.location.protocol}//${window.location.host}`;
  }

  return "";
};


const api = axios.create({
  baseURL: getApiBaseUrl(),
  withCredentials: true,
});

api.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401 || error.response?.status === 403) {
      window.location.href = "/login";
    }
    return Promise.reject(error);
  }
);

const PayrollManagement = ({ onBack }) => {
  const navigate = useNavigate();
  
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedStatus, setSelectedStatus] = useState("All Status");
  const [selectedMonth, setSelectedMonth] = useState("All Months");
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState("");
  const [isEditOpen, setIsEditOpen] = useState(false);
  const [editRecord, setEditRecord] = useState(null);
  const [isViewOpen, setIsViewOpen] = useState(false);
  const [viewRecord, setViewRecord] = useState(null);



  const [payrollRecords, setPayrollRecords] = useState([]);

const fetchPayrollRecords = useCallback(async (signal) => {
  try {
    setLoading(true);
    setLoadError("");

    const res = await api.get("/api/payroll", { signal });
    const data = res.data;

    let records = [];
    if (Array.isArray(data)) records = data;
    else if (Array.isArray(data.data)) records = data.data;
    else if (Array.isArray(data.payrolls)) records = data.payrolls;
    else if (Array.isArray(data.records)) records = data.records;
    else if (Array.isArray(data.content)) records = data.content;

    const normalizedRecords = records.map(record => ({
      ...record,
       id: record.id || record.payrollId,
      userId: record.userId || record.user_id,
      userName: record.userName || record.username || "Unknown",
      employeeId: record.employeeId || record.employee_id || `EMP-${record.userId}`,
      employeeName: record.employeeName || record.employee_name || record.userName || "Unknown",
      joiningDate: record.joiningDate || record.joining_date,
      basicSalary: Number(record.basicSalary || record.basic_salary || 0),
      totalEarnings: Number(record.totalEarnings || record.total_earnings || 0),
      totalDeductions: Number(record.totalDeductions || record.total_deductions || 0),
      netSalary: Number(record.netSalary || record.net_salary || 0),
      lopDays: Number(record.lopDays || record.lop_days || 0),
      payrollMonth: record.payrollMonth || record.payroll_month,
      autoGenerated: Boolean(record.autoGenerated || record.auto_generated),
      source: record.autoGenerated ? "Auto Generated" : "Manual Entry",
    }));

    setPayrollRecords(normalizedRecords);
  } catch (err) {
    if (err.name !== "CanceledError") {
      setLoadError(err.response?.data?.message || "Failed to load payroll records");
    }
  } finally {
    setLoading(false);
  }
}, []);


useEffect(() => {
  const controller = new AbortController();
  fetchPayrollRecords(controller.signal);

  return () => controller.abort();
}, [fetchPayrollRecords]);

const refreshPayrollRecords = () => {
  const controller = new AbortController();
  fetchPayrollRecords(controller.signal);
};


  const formatDate = (dateStr) => {
    if (!dateStr) return "N/A";
    try {
      const date = new Date(dateStr);
      return date.toLocaleDateString('en-IN', { 
        year: 'numeric', 
        month: 'short' 
      });
    } catch {
      return dateStr;
    }
  };

  const availableMonths = useMemo(() => {
  const months = new Set();

  payrollRecords.forEach(record => {
    if (record.payrollMonth) {
      months.add(formatDate(record.payrollMonth));
    }
  });

  return Array.from(months).sort((a, b) => new Date(b) - new Date(a));
}, [payrollRecords]);

  // ✅ Client-side filtering (until backend supports query params)
  const filteredRecords = useMemo(() => {
    return payrollRecords.filter(record => {
      const matchesSearch = !searchTerm || 
        record.employeeName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        record.userName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        record.employeeId?.toString().includes(searchTerm) ||
        record.userId?.toString().includes(searchTerm);

      const recordStatus = record.status || "Pending";

const matchesStatus =
  selectedStatus === "All Status" ||
  recordStatus === selectedStatus;

let matchesMonth = true;

if (selectedMonth !== "All Months") {
  const selectedMonthName = selectedMonth.split(" ")[0]; // "January"
  const recordMonth = formatDate(record.payrollMonth);   // "Jan 2025"

  matchesMonth = recordMonth?.includes(selectedMonthName.slice(0, 3));
}

return matchesSearch && matchesStatus && matchesMonth;

    });
  }, [payrollRecords, searchTerm, selectedStatus, selectedMonth]);


  const formatJoiningDate = (dateStr) => {
    if (!dateStr) return "N/A";
    try {
      const date = new Date(dateStr);
      return date.toLocaleDateString('en-IN', { 
        year: 'numeric', 
        month: 'short',
        day: 'numeric'
      });
    } catch {
      return dateStr;
    }
  };

  const getStatusBadge = (status) => {
    const statusMap = {
      "Pending": { bg: "bg-yellow-50", text: "text-yellow-700", border: "border-yellow-200" },
      "Approved": { bg: "bg-green-50", text: "text-green-700", border: "border-green-200" },
      "Paid": { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-200" },
      "PENDING": { bg: "bg-yellow-50", text: "text-yellow-700", border: "border-yellow-200" },
      "APPROVED": { bg: "bg-green-50", text: "text-green-700", border: "border-green-200" },
      "PAID": { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-200" },
    };
    const config = statusMap[status] || statusMap["Pending"];
    return `inline-flex rounded-full ${config.bg} ${config.text} px-3 py-1 text-xs font-medium border ${config.border}`;
  };

  const handleManualEntry = () => {
    navigate("/admin/manualentry");
  };

const handleViewDetails = (record) => {
  setViewRecord(record);
  setIsViewOpen(true);
};

const handleExport = async () => {
  try {
    const params = {
      status: selectedStatus !== "All Status" ? selectedStatus : null,
      month: selectedMonth !== "All Months" ? selectedMonth : null,
    };

    const response = await api.get("/api/payroll/export", {
      params,
      responseType: "blob",
    });

    const blob = new Blob([response.data], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });

    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "payroll-report.xlsx";
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Export failed", error);
    alert("Failed to export payroll data");
  }
};



const handleEdit = (record) => {
  setEditRecord(record);
  setIsEditOpen(true);
};


  const handleDelete = async (record) => {
  const confirmed = window.confirm(
    `Are you sure you want to delete payroll for ${record.employeeName}?`
  );

  if (!confirmed) return;

  try {
    await api.delete(`/api/payroll/${record.id}`);
    refreshPayrollRecords(); // reload table
  } catch (error) {
    console.error("Delete failed", error);
    alert("Failed to delete payroll");
  }
};

const handleUpdatePayroll = async () => {
  try {
await api.put(`/api/payroll/${editRecord.id}`, {
  basicSalary: editRecord.basicSalary,
  otherDeductions: editRecord.totalDeductions,
  status: editRecord.status?.toUpperCase(),
});


    setIsEditOpen(false);
    setEditRecord(null);
    refreshPayrollRecords();
  } catch (error) {
    console.error("Update failed", error);
    alert("Failed to update payroll");
  }
};




  return (
    <div className="w-full h-full bg-[#F9FAFF] p-6">
      {/* Back Button */}
      <button
        onClick={onBack}
        className="mb-4 flex items-center gap-2 text-sm font-medium text-[#011A8B] hover:underline"
      >
        <ArrowLeft size={18} />
        <span>Back to Finance Dashboard</span>
      </button>

      {/* Header */}
      <div className="mb-6 flex flex-col justify-between gap-4 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm lg:flex-row lg:items-center">
        <div>
          <h1 className="text-2xl font-semibold text-[#011A8B]">
            Payroll Management
          </h1>
          <p className="text-sm text-gray-500">
            Manage all payroll records ({filteredRecords.length} shown)
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <button
  onClick={refreshPayrollRecords}
  disabled={loading}
  className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm transition hover:bg-gray-50 disabled:opacity-50"
>

            <RefreshCw size={18} className={loading ? "animate-spin" : ""} />
            <span>{loading ? "Refreshing..." : "Refresh"}</span>
          </button>

          <button
            onClick={handleManualEntry}
            className="inline-flex items-center gap-2 rounded-xl bg-[#011A8B] px-4 py-2 text-sm font-medium text-white shadow-sm transition hover:bg-[#020f5d]"
          >
            <Plus size={18} />
            <span>Manual Entry</span>
          </button>

                   <button
  onClick={handleExport}
  className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm transition hover:bg-gray-50"
>
  <FileText size={18} />
  <span>Export</span>
</button>

        </div>
      </div>

      {/* Filters */}
      <div className="mb-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
        <div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          {/* Search */}
          <div className="relative w-full max-w-md">
            <Search
              className="pointer-events-none absolute left-3 top-2.5 text-gray-400"
              size={18}
            />
            <input
              type="text"
              placeholder="Search by employee name or ID..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full rounded-xl border border-gray-200 bg-[#F9FAFF] py-2.5 pl-10 pr-4 text-sm text-gray-800 placeholder:text-gray-400 focus:border-[#011A8B] focus:outline-none focus:ring-2 focus:ring-[#011A8B]/20"
            />
          </div>

          {/* Quick Filters */}
          <div className="flex gap-3">
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="rounded-xl border border-gray-200 bg-[#F9FAFF] px-4 py-2.5 text-sm text-gray-700 focus:border-[#011A8B] focus:outline-none focus:ring-2 focus:ring-[#011A8B]/20"
            >
              <option>All Status</option>
              <option>Pending</option>
              <option>Approved</option>
              <option>Paid</option>
            </select>
            
<select
  value={selectedMonth}
  onChange={(e) => setSelectedMonth(e.target.value)}
  className="rounded-xl border border-gray-200 bg-[#F9FAFF] px-4 py-2.5 text-sm"
>
  <option>All Months</option>
  {availableMonths.map(month => (
    <option key={month} value={month}>
      {month}
    </option>
  ))}
</select>

          </div>
        </div>
      </div>

      {/* Records Table */}
      <div className="rounded-2xl border border-gray-200 bg-white shadow-sm">
        <div className="px-6 py-4 border-b border-gray-100">
          <h2 className="text-lg font-semibold text-[#011A8B]">
            Payroll Records ({filteredRecords.length})
          </h2>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gradient-to-r from-[#EEF0FF] to-[#E0E7FF]">
              <tr>
                <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Employee Name
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Employee ID
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Joining Date
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Month
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Source
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Basic Salary
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Total Earnings
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Deductions
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Net Salary
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Status
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  LOP Days
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 bg-white">
              {loading ? (
                <tr>
                  <td colSpan={12} className="px-6 py-12 text-center">
                    <Loader2 className="mx-auto h-8 w-8 animate-spin text-[#011A8B]" />
                    <p className="mt-2 text-sm text-gray-500">Loading payroll records...</p>
                  </td>
                </tr>
              ) : loadError ? (
                <tr>
                  <td colSpan={12} className="px-6 py-12 text-center">
                    <p className="text-sm font-medium text-red-600">{loadError}</p>
                    <button
  onClick={refreshPayrollRecords}
  className="mt-2 rounded-lg bg-red-50 px-4 py-2 text-sm text-red-700 hover:bg-red-100"
>
  Retry
</button>

                  </td>
                </tr>
              ) : filteredRecords.length === 0 ? (
                <tr>
                  <td colSpan={12} className="px-6 py-12 text-center">
                    <FileText className="mx-auto h-12 w-12 text-gray-400" />
                    <p className="mt-2 text-sm font-medium text-gray-900">No payroll records found</p>
                    <p className="text-sm text-gray-500">
                      {searchTerm ? "Try adjusting your search" : "No records match your filters"}
                    </p>
                  </td>
                </tr>
              ) : (
                filteredRecords.map((record) => (
                 <tr key={`${record.userId}-${record.payrollMonth}`} className="hover:bg-gray-50">
                    <td className="px-6 py-4">
                      <div className="flex flex-col">
                        <span className="text-sm font-semibold text-gray-900">
                          {record.employeeName || record.userName || "Unknown"}
                        </span>
                      </div>
                    </td>
                    <td className="px-4 py-4">
                      <span className="text-sm font-mono text-gray-700">
                        {record.employeeId}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span className="text-sm text-gray-700">
                        {formatJoiningDate(record.joiningDate)}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span className="text-sm text-gray-900">
                        {formatDate(record.payrollMonth)}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                        record.autoGenerated 
                          ? 'bg-green-100 text-green-800' 
                          : 'bg-blue-100 text-blue-800'
                      }`}>
                        {record.autoGenerated ? "Auto" : "Manual"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-mono text-gray-900">
                        ₹{record.basicSalary?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-mono text-gray-900">
                        ₹{record.totalEarnings?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-mono text-gray-900">
                        ₹{record.totalDeductions?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-bold text-emerald-600">
                        ₹{record.netSalary?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span className={getStatusBadge(record.status || "Pending")}>
                        {record.status || "Pending"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm text-gray-900">{record.lopDays || 0}</span>
                    </td>
                    <td className="px-4 py-4">
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => handleViewDetails(record)}
                          className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-gray-200 bg-white text-gray-600 shadow-sm transition hover:bg-blue-50 hover:text-blue-600"
                          title="View Details"
                        >
                          <Eye size={16} />
                        </button>
<button
  onClick={() => handleEdit(record)}
  disabled={record.status === "PAID"}
  className={`inline-flex h-9 w-9 items-center justify-center rounded-full border shadow-sm transition
    ${record.status === "PAID"
      ? "bg-gray-100 text-gray-400 cursor-not-allowed"
      : "bg-white text-gray-600 hover:bg-gray-50"
    }`}
  title={record.status === "PAID" ? "Paid payroll cannot be edited" : "Edit"}
>
  <Edit size={16} />
</button>


                        <button
  onClick={() => handleDelete(record)}
  className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-gray-200 bg-white text-red-600 shadow-sm transition hover:bg-red-50 hover:text-red-700"
  title="Delete"
>
  <Trash2 size={16} />
</button>

                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

 {/* ================= EDIT MODAL ================= */}
{isEditOpen && editRecord && (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
    <div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-lg">
      <h2 className="mb-4 text-xl font-semibold text-[#011A8B]">
        Edit Payroll – {editRecord.employeeName}
      </h2>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="text-sm text-gray-600">Basic Salary</label>
          <input
            type="number"
            value={editRecord.basicSalary}
            onChange={(e) =>
              setEditRecord({
                ...editRecord,
                basicSalary: Number(e.target.value),
              })
            }
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </div>

        <div>
          <label className="text-sm text-gray-600">Total Deductions</label>
          <input
            type="number"
            value={editRecord.totalDeductions}
            onChange={(e) =>
              setEditRecord({
                ...editRecord,
                totalDeductions: Number(e.target.value),
              })
            }
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </div>

        <div>
          <label className="text-sm text-gray-600">Status</label>
          <select
            value={editRecord.status || "Pending"}
            onChange={(e) =>
              setEditRecord({
                ...editRecord,
                status: e.target.value,
              })
            }
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          >
            <option>Pending</option>
            <option>Approved</option>
            <option>Paid</option>
          </select>
        </div>
      </div>

      <div className="mt-6 flex justify-end gap-3">
        <button
          onClick={() => {
            setIsEditOpen(false);
            setEditRecord(null);
          }}
          className="rounded-lg border px-4 py-2 text-sm"
        >
          Cancel
        </button>

        <button
          onClick={handleUpdatePayroll}
          className="rounded-lg bg-[#011A8B] px-4 py-2 text-sm text-white"
        >
          Save Changes
        </button>
      </div>
    </div>
  </div>
)}

{/* ================= VIEW MODAL ================= */}
{isViewOpen && viewRecord && (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
    <div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-lg">
      <h2 className="mb-4 text-xl font-semibold text-[#011A8B]">
        Payroll Details – {viewRecord.employeeName}
      </h2>

      <div className="grid grid-cols-2 gap-4 text-sm">
        <div>
          <p className="text-gray-500">Employee</p>
          <p>{viewRecord.employeeName} ({viewRecord.employeeId})</p>
        </div>
        <div>
          <p className="text-gray-500">Joining Date</p>
          <p>{formatJoiningDate(viewRecord.joiningDate)}</p>
        </div>
        <div>
          <p className="text-gray-500">Month</p>
          <p>{formatDate(viewRecord.payrollMonth)}</p>
        </div>
        <div>
          <p className="text-gray-500">Status</p>
          <p>{viewRecord.status}</p>
        </div>

        <div>
          <p className="text-gray-500">Basic Salary</p>
          <p>₹{viewRecord.basicSalary.toLocaleString("en-IN")}</p>
        </div>
        <div>
          <p className="text-gray-500">Total Earnings</p>
          <p>₹{viewRecord.totalEarnings.toLocaleString("en-IN")}</p>
        </div>
        <div>
          <p className="text-gray-500">Total Deductions</p>
          <p>₹{viewRecord.totalDeductions.toLocaleString("en-IN")}</p>
        </div>
        <div>
          <p className="text-gray-500">Net Salary</p>
          <p className="font-semibold text-emerald-600">
            ₹{viewRecord.netSalary.toLocaleString("en-IN")}
          </p>
        </div>

        <div>
          <p className="text-gray-500">LOP Days</p>
          <p>{viewRecord.lopDays}</p>
        </div>
        <div>
          <p className="text-gray-500">Source</p>
          <p>{viewRecord.source}</p>
        </div>
      </div>

      <div className="mt-6 flex justify-end">
        <button
          onClick={() => {
            setIsViewOpen(false);
            setViewRecord(null);
          }}
          className="rounded-lg border px-4 py-2 text-sm"
        >
          Close
        </button>
      </div>
    </div>
  </div>
)}


  </div>

  );
};

export default PayrollManagement;
